spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      routes:
        - id: productservice
          uri: lb://productservice
          predicates:
            - Path=/api/v1/products/**
        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/api/v1/orders/**
        - id: eureka
          uri: http://localhost:8888
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true


